### ISSUE TITLE
Issues training on my own dataset 

### ISSUE THREAD

**Issue by tluth** [pierluigiferrari/ssd_keras#77] opened 2018-03-06 13:04 UTC
Hi, 

Firstly, thanks for your work. This was a great help in learning more about SSD (and object detection in general). 

So I've attempted to follow your training notebook using my own dataset consisting of 400 images (split 80:20 for training/val). My images are mostly around 300x300-600x600 and I'm trying to detect one class of object: boats in satellite imagery. I thought that boats wouldn't be too hard to detect since they all stand out from the background, have a relatively similar colour, and shape. 

I tried training on both the 300 and 512 model, and also tried starting with the weights from VGG16 as well as weights from COCO and also a sub-sampled version of the COCO weights (after following your tutorial). 

After running the training with a batch size of 32, for 32 epochs, it stopped before the end of the process as the loss wasn't reducing. It got down to around 8. On testing, if I play with the prediction thresholds I can get some predictions but they seem to be arbitrarily located and the confidences are all the same or similar. I've attached some examples. 

These results have been more or less the same regardless of the different training methods I tried. Any tips or advice on training would be hugely appreciated, and if these results give you any clue as to what I'm doing wrong, I'd be grateful for your advice. 

<img width="429" alt="screen shot 2018-03-06 at 1 26 23 pm" src="https://user-images.githubusercontent.com/35136057/37033727-33ca044c-2147-11e8-969f-e667c4880bd9.png">
<img width="448" alt="screen shot 2018-03-06 at 1 32 49 pm" src="https://user-images.githubusercontent.com/35136057/37033728-33f83010-2147-11e8-8b7e-d945180a209b.png">

**Comment by pierluigiferrari** [comment] 2018-03-06 18:41
Your results indicate that the model is learning nothing at all. First, note that if the model is learning only one class, a confidence of 50% means maximal uncertainty, i.e. the model has learned nothing.

Detecting boats in satellite imagery should indeed be a task at which SSD should be able to do a decent job, so something is likely wrong here.  The first questions that come to my mind:

1. Could there be an issue somewhere with the data being fed to the model? Maybe something as simple as an incorrect coordinate order or format when parsing the labels or something like that. This is the first potential source of error I'd focus on: Anything that might lead to the model being fed faulty data.
2. You say you're getting the loss down to around 8. Where does it start?
3. Stick with the sub-sampled COCO model as your starting point for the sake of getting to the bottom of this. What changes, if any, did you make to the training notebook?

**Comment by tluth** [comment] 2018-03-06 19:05
Thanks for the quick response and the suggestions! I really appreciate it. 

During my first big training run (using the subsampled weights from the COCO data), which was done using the SSD512 model, with batch size 32, set to train for 32 epochs, the output for the first epoch looked like this: 
```
Epoch 1/32
12/13 [==========================>...] - ETA: 4:34 - loss: 13.3480   Epoch 00001: val_loss improved from inf to 11.70267, saving model to ssd512newest2_weights_epoch-01_loss-13.3165_val_loss-11.7027_coco.h5
13/13 [==============================] - 3433s 264s/step - loss: 13.2928 - val_loss: 11.7027
```
The final epoch looked like this:
```
Epoch 14/32
12/13 [==========================>...] - ETA: 4:21 - loss: 6.3138 Epoch 00014: val_loss did not improve
13/13 [==============================] - 3272s 252s/step - loss: 6.2835 - val_loss: 5.7181
```
This was the lowest loss values I've seen, presumably as it was the highest batch size/epochs I'd trained with. Generally the others started with a loss of around 15-25 and got to around 8. 

I've tried the SSD300 training notebook with practically no changes other than number of classes. But I didn't leave this training for very long as it was mostly a test, and I expected to get better results by using the 512 model and reducing the scale values. When I did the above training on the SSD512 model, the only things I really changed was in the following part of the code: 

```
img_height = 512 # Height of the input images
img_width = 512 # Width of the input images
img_channels = 3 # Number of color channels of the input images
subtract_mean = [23, 28, 26] # The per-channel mean of the images in the dataset
swap_channels = True # The color channel order in the original SSD is BGR
n_classes = 1 # Number of positive classes, e.g. 20 for Pascal VOC, 80 for MS COCO
scales_voc = [0.1, 0.2, 0.37, 0.54, 0.71, 0.88, 1.05] # The anchor box scaling factors used in the original SSD300 for the Pascal VOC datasets
scales_coco = [0.07, 0.15, 0.33, 0.51, 0.69, 0.87, 1.05] # The anchor box scaling factors used in the original SSD300 for the MS COCO datasets
scales_custom = [0.04, 0.06, 0.08, 0.1, 0.15, 0.33, 0.51, 0.69]
scales = scales_custom
aspect_ratios = [[1.0, 2.0, 0.5],
                 [1.0, 2.0, 0.5, 3.0, 1.0/3.0],
                 [1.0, 2.0, 0.5, 3.0, 1.0/3.0],
                 [1.0, 2.0, 0.5, 3.0, 1.0/3.0],
                 [1.0, 2.0, 0.5, 3.0, 1.0/3.0],
                 [1.0, 2.0, 0.5],
                 [1.0, 2.0, 0.5]] # The anchor box aspect ratios used in the original SSD300; the order matters
two_boxes_for_ar1 = True
steps = [8, 16, 32, 64, 100, 300, 512] # The space between two adjacent anchor box center points for each predictor layer.
offsets = [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5] # The offsets of the first anchor box center points from the top and left borders of the image as a fraction of the step size for each predictor layer.
limit_boxes = False # Whether or not you want to limit the anchor boxes to lie entirely within the image boundaries
variances = [0.1, 0.1, 0.2, 0.2] # The variances by which the encoded target coordinates are scaled as in the original implementation
coords = 'centroids' # Whether the box coordinates to be used as targets for the model should be in the 'centroids', 'corners', or 'minmax' format, see documentation
normalize_coords = True
```
I also added the extra convolutional layer for the 512 model in the following section:

```
predictor_sizes = [model.get_layer('conv4_3_norm_mbox_conf').output_shape[1:3],
                   model.get_layer('fc7_mbox_conf').output_shape[1:3],
                   model.get_layer('conv6_2_mbox_conf').output_shape[1:3],
                   model.get_layer('conv7_2_mbox_conf').output_shape[1:3],
                   model.get_layer('conv8_2_mbox_conf').output_shape[1:3],
                   model.get_layer('conv9_2_mbox_conf').output_shape[1:3],
                   model.get_layer('conv10_2_mbox_conf').output_shape[1:3]]
```

I hope that helps. Thanks again for your advice. I'll keep investigating based on what you said.

**Comment by tluth** [comment] 2018-03-06 19:11
Oh, and in regards to the data input. I've used the app RectLabel for producing the labels, which produces xml files in the same style as Pascal VOC data. I even deleted the one line in the label files which varies from the Pascal style (even though it's redundant).

My ground truth bounding boxes for testing were produced in the same manner and are displayed perfectly in the testing part of the training notebook, so I assumed parsing of the labels was not an issue.

**Comment by pierluigiferrari** [comment] 2018-03-06 19:33
Two things I notice: (1) If you're using one of the pre-trained models, even if it's just the VGG-16 weights, you should not change `subtract_means` from its preset value. I should probably add a note about that in the notebook. (2) Stick with the default MS COCO scaling factors for the trial runs, just to exclude another potential source of error. Neither of these two points can possibly be the sole reason why the model predicts all boxes at 50% confidence, but they are important nonetheless.

Beyond that I don't have any ideas at the moment. If the parsed ground truth labels are in the right format (i.e. `(class_id, xmin, ymin, xmax, ymax)`) and you stick with the original SSD300 or SSD512 configuration (i.e. don't touch the scaling factors or the input mean normalization values) and the model still learns nothing, then the next potential source of error would be the sub-sampled COCO weights, but the weights that I have sub-sampled so far worked. Addressing the two points above very likely won't solve the problem, but it would be interesting to see if it changes anything nonetheless.

**Comment by tluth** [comment] 2018-03-06 19:56
Okay, I've gone back to the original SSD300 model with the vgg16 weights provided. 

I should also add, that the images provided were only from one of my training tests. There were others with higher confidence values (some at around 0.9) but they always produced huge numbers of predictions all with the same values.

**Comment by tluth** [comment] 2018-03-06 21:15
Training just finished. Obviously not enough training to bring down the loss significantly. Training loss stayed in the thousands while validation loss was around 6-7. 

One thing I found interesting was that when the confidence threshold was at 0.49 for testing, the IOU threshold had no effect on the predictions. Even when it was set to 1, this box still displayed, despite the fact there's clearly no intersection at all. 

<img width="392" alt="screen shot 2018-03-06 at 10 10 00 pm" src="https://user-images.githubusercontent.com/35136057/37058734-bcaed190-218b-11e8-8cb9-5550b8354633.png">

When the confidence threshold was set to 0.48, changing the IOU threshold did have some effect. 

Still, no results to speak of.

**Comment by pierluigiferrari** [comment] 2018-03-06 21:42
The training loss stayed in the thousands while the validation loss got down to around 6-7?! This is making less and less sense ;).

As a side note, the `iou_threshold` has nothing to do with the overlap of a predicted box with any of the ground truth boxes. It is just the criterion based on which the non-maximum suppression decides which predicted boxes are thrown away and which are kept. NMS will always result in at least one predicted box (the one with the highest confidence).

If you don't mind sharing the dataset, I'll give it a try myself.

**Comment by tluth** [comment] 2018-03-06 22:44
Yeah sure, that'd be great to see if you can get it working. I'll email you a link as soon as I can.

**Comment by quillkong** [comment] 2018-03-25 08:26
I have similar problem, when trying to detect buildings from satellite imagery. Did you find the cause of the problem?

**Comment by tluth** [comment] 2018-03-25 13:01
Hey quillkong, I still haven't resolved the issue. I plan to work on it more later this week, and I'll let you know if I make any progress.

**Comment by pierluigiferrari** [comment] 2018-03-27 14:01
No guarantees, but I hope I'll get around to training a model on your dataset on the weekend.

**Comment by tluth** [comment] 2018-03-30 06:48
Wow. Thanks so much for working on this. I've got a fairly busy weekend,
but I'll make some time to go through your notebook and try it out for
myself.

I'll let you know if I find the cause of my problems too.

Thanks again.

All the best,

Tom

On Thu, Mar 29, 2018 at 9:40 PM, Pierluigi Ferrari <notifications@github.com

**Comment by juiceboxjoe** [comment] 2018-04-13 21:09
@pierluigiferrari I'm attempting to replicate your results with a satellite image dataset. I downloaded your notebook from [here](https://drive.google.com/open?id=19B20zzjxaMV7WDFycB1A9FstJaBTg91V) and modified:

- image size
- path to train/val images/labels
- path to indicate where to store checkpoints
- changed centroids to minmax usage

When using the data_augmentation_chain_satellite.py (cell # 7 of the notebook you shared in your previous post) I'm getting the following error:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-8-3a8eec16ab1f> in <module>()
     17                                                     bounds_validator=(0.5, 1.0),
     18                                                     n_boxes_min=1,
---> 19                                                     background=(0,0,0))
     20 
     21 resize = Resize(height=img_height,

~/home/blandron/ssd_keras_2/ssd_keras/data_generator/data_augmentation_chain_satellite.py in __init__(self, resize, random_brightness, random_contrast, random_saturation, random_hue, random_flip, random_translate, random_scale, n_trials_max, clip_boxes, overlap_criterion, bounds_box_filter, bounds_validator, n_boxes_min, background, labels_format)
     70         self.box_filter = BoxFilter(overlap_criterion=self.overlap_criterion,
     71                                     bounds=self.bounds_box_filter,
---> 72                                     labels_format=self.labels_format)
     73 
     74         # Determines whether the result of the transformations is a valid training image.

TypeError: __init__() got an unexpected keyword argument 'bounds'
```

Indeed BoxFilter() does not specify a `bounds` argument. Can you tell me which commit has a BoxFilter() implementation that works with that notebook?

Thanks in  advance.

**Comment by pierluigiferrari** [comment] 2018-04-13 23:01
@juiceboxjoe Yeah, the `BoxFilter()` API has changed slightly, the former `bounds` argument is now called `overlap_bounds`.

As mentioned above though, the data augmentation chain I linked above really isn't great, it was just good enough to figure out whether I can get the training to work on the OP's dataset.

I've just added a better data augmentation chain for bird's eye view datasets in the latest commit, [check it out](https://github.com/pierluigiferrari/ssd_keras/blob/master/data_generator/data_augmentation_chain_satellite.py). The augmentation chain above only works for constant-size images and it doesn't introduce any random deformations. The new chain works for constant- or variable-size images, introduces slight random deformations, and adds random rotations.

**Comment by juiceboxjoe** [comment] 2018-04-16 14:11
Sweet! Thanks!

**Comment by pierluigiferrari** [comment] 2018-04-17 18:49
@tluth I'll close this issue for now, feel free to reopen it if it's still relevant.

**Closed by pierluigiferrari** 2018-04-17 18:49 UTC

**Comment by tluth** [comment] 2018-04-17 20:24
Cheers. I've been kind of busy at the moment, but I've just left your ssd512 model training on my dataset with the new data augmentation chain. I'll let you know how my results turn out. 

Tom

**Comment by Purav-Zumkhawala** [comment] 2019-02-06 07:01
Hi I am trying to train SSD model on my custom dataset. 
Initially I trained it using image size 300 x 300 and voc scaling factors using only the VGG 16 weights.
After training when I tried to test it, I found that a class was not getting predicted ever.
I have kept everything as it is and I think it is due to the scaling factors and aspect ratios. 
A person detection bounding box is sometimes the size of a cap and other times it is normal.

Can you advice me on how to decide the aspect ratios and find corresponding scaling factors for my dataset ?

I am trying to predict a person and a cap.

It would be a great help
